language: node_js

sudo: required

services:
  - docker

cache: yarn

before_install:
  - npm i nsp -g
  - npm i snyk -g

before_script:
  - snyk auth ${SNYK_TOKEN} -d
  - snyk protect

after_script:
  - snyk monitor

  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

  - APPLICATION_VERSION=$(./.bin/version)
  - DOCKER_IMAGE=nodejs-boilerplate
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - docker build -t $DOCKER_IMAGE .

  - docker tag $DOCKER_IMAGE $TRAVIS_REPO_SLUG:$TAG
  - docker tag $DOCKER_IMAGE $TRAVIS_REPO_SLUG:$APPLICATION_VERSION

  - docker push $TRAVIS_REPO_SLUG:$TAG
  - docker push $TRAVIS_REPO_SLUG:$APPLICATION_VERSION

  - docker login --email=_ --username=_ --password=$HEROKU_API_TOKEN registry.heroku.com
  - docker tag $DOCKER_IMAGE registry.heroku.com/$HEROKU_APPLICATION/app
  - heroku container:push app
