language: node_js

sudo: required

services:
  - docker

cache: yarn

before_install:
  - npm i nsp -g
  - npm i snyk -g

before_script:
  - snyk auth ${SNYK_TOKEN} -d
  - snyk protect

after_success:
  - snyk monitor
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - APPLICATION_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
  - DOCKER_REPO=$DOCKER_REPO
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $DOCKER_REPO:$COMMIT .
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TAG
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$APPLICATION_VERSION
  - docker push
