language: node_js

sudo: required

services:
  - docker

cache: yarn

before_script:
  - snyk auth ${SNYK_TOKEN} -d
  - snyk protect

script:
  make test-docker
  make docker-build
  make docker-cleanup

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - snyk monitor