image: node:6.10.0
pipelines:
  default:
    - step:
        script:
          # installing dependencies
          - npm i nsp -g
          - npm i snyk -g
          - npm i

          # initial setup
          - snyk auth ${SNYK_TOKEN} -d
          - snyk protect

          # running tests
          - npm test

          # monitor for new vulnerabilities
          - if [ $BITBUCKET_BRANCH == "master" ]; then snyk monitor; fi;